### ISSUE TITLE
Define output worker file path and name

### ISSUE THREAD

**Issue by brucejcw** [webpack-contrib/worker-loader#36] opened 2016-11-01 08:25 UTC
how to define? [example](https://github.com/webpack/webpack/blob/master/examples/web-worker/webpack.config.js) doesn't work

**Comment by zhanghaowx** [comment] 2016-12-13 17:36
I am also very curious to learn how to do it correctly

**Comment by mariotacke** [comment] 2017-01-09 18:31
Did you ever figure out how to do this with webpack 1 without the inline option?

**Comment by zhanghaowx** [comment] 2017-03-11 01:18
@mariotacke 

        worker: {
            output: {
                filename: "developer/dist/[hash].worker.js",
            }
        }
should do the trick to put your worker file into the folder you want. However, you cannot use 

    [name].worker.js
if you have more than one worker file. But you can watch https://github.com/webpack-contrib/worker-loader/pull/22 and hopefully it will get merged soon.

**Comment by drcmda** [comment] 2017-05-10 19:54
Couldn't it simply use the chunks pattern? Most configs already have:

    chunkFilename: 'build/chunk.[id].js',

The problem is that we distribute our lib, and this forces customers to add this stuff to their configs or otherwise the worker is dumped into the root folder with a random hashname.

**Comment by TrySound** [comment] 2017-07-04 22:28
Name option should work now

**Closed by TrySound** 2017-07-04 22:28 UTC
Labels: flag: Has pull request, priority: 4 (important), severity: 4 (inconvenient), type: Feature
