### ISSUE TITLE
duplicate chunks

### ISSUE THREAD

**Issue by FranckFreiburger** [webpack-contrib/worker-loader#86] opened 2017-08-05 13:22 UTC
I use PDF.js library that use a web worker for pdf rendering (pdf.worker.js).
PDF.js also has a fallback mode for browsers that does not support web workers (it just use `pdf.worker.js` without a web worker).

```
var pdfjs = require('./build/pdf.js');
var PdfjsWorker = require('worker-loader!./build/pdf.worker.js');
...
pdfjs.PDFJS.workerPort = new PdfjsWorker();
```
[source](https://github.com/mozilla/pdfjs-dist/blob/e5229d685258847bbbc98bac36cbda4e1bbb5445/webpack.js#L17-L26)

`build/pdf.js` also requires the `pdf.worker.js` as fallback
```
      worker = require('./pdf.worker.js');
```
[source](https://github.com/mozilla/pdfjs-dist/blob/e5229d685258847bbbc98bac36cbda4e1bbb5445/build/pdf.js#L1831)

All of this lead to a duplicate of `pdf.worker.js` (> 600KB). 

Is it possible to ask worker-loader to keep pdf.worker.js common ?

(maybe related to issue #70)

**Comment by michael-ciniawsky** [comment] 2017-10-12 10:49
Duplicate of #70

**Closed by michael-ciniawsky** 2017-10-12 10:49 UTC
