### ISSUE TITLE
How can I use this to bundle a library?

### ISSUE THREAD

**Issue by FezVrasta** [webpack-contrib/worker-loader#110] opened 2017-11-22 12:22 UTC
So, I found this question on SO:
https://stackoverflow.com/questions/42203665/webpack-worker-loader-how-to-make-it-work-as-a-dependency

But nobody ever replied. So I'm asking here to see if you guys have any insights.

I'd like to bundle my library and import it inside another webpack project.

Right now if I don't use the `inline` option the consumer app will not find the worker file (because I guess webpack doesn't copy it into the build folder).

How can I do?

**Comment by michael-ciniawsky** [comment] 2017-12-04 07:49
I need more info about how in particular you intend to build the lib, for the SO question I think `options.publicPath` should work

**Comment by FezVrasta** [comment] 2017-12-04 07:56
How can public path work if I don't know what will be the public path? AFAIK you can't define a path relative to the webpack bundle

**Comment by amirsimhi** [comment] 2018-06-18 16:07
any updates about this issue? I'm facing the same problem

**Comment by FezVrasta** [comment] 2018-06-18 16:33
No news unfortunately

**Comment by shellscape** [comment] 2018-06-18 16:53
@amirsimhi if you don't see any new activity in the issue thread, then there has been no updates. please don't pollute an issue thread by posting questions of that type. it does not contribute to the issue nor the discussion.

**Comment by evilebottnawi** [comment] 2020-07-13 14:12
Fixed in the master branch

**Closed by evilebottnawi** 2020-07-13 14:12 UTC
Labels: flag: Needs more info

**Comment by manasb-uoe** [comment] 2020-10-07 13:14
> Fixed in the master branch

So I seem to be stuck on the same problem - what was the fix in the end?

**Comment by evilebottnawi** [comment] 2020-10-07 13:18
@manasb-uoe update `worker-loader` to the latest version

**Comment by slutske22** [comment] 2020-12-13 05:43
I'm wondering about this myself.  How to tell worker-loader to reference the worker files relative to the file that says `new Worker('path_should_be_relative_to_the_file_this_line_is_in')`.  I feel like worker-loader needs a `relativePath` option, which would be a boolean that tells worker loader to maintain the relative relationship between worker script and the place where the worker script is imported.

**Comment by alexander-akait** [comment] 2020-12-14 12:21
@slutske22 webpack@5 supports syntax `new Worker(new URL('./path/to/worker.js', import.meta.url));`

**Comment by Danik-Barinshtein** [comment] 2021-01-29 22:57
@alexander-akait  

Hey guys - just trying to follow this thread as I am in a similar situation.

If I use inline it works, however the issue is that I am trying to implement a SharedWorker - and if I use inline they treat it as a brand new script and dont maintain the Shared functionality.

As for using webpack@5 - that's not an option currently to upgrade.

Seeing if there are any suggestions?
