### ISSUE TITLE
TypeError: Cannot read property 'outputOptions' of undefined

### ISSUE THREAD

**Issue by fredley** [webpack-contrib/worker-loader#129] opened 2018-02-26 13:32 UTC
[TS 2.6.2, webpack 4.0.0, worker-loader 1.1.1]

**App.ts**

```import WorkerOne = require("worker-loader?inline!./workers/WorkerOne")```

**Elsewhere.ts**

```import WorkerTwo = require("worker-loader?inline!./workers/WorkerTwo")```

**custom.d.ts**

```
declare module "worker-loader?inline!*" {
  export class WorkerOne extends Worker {
    constructor();
  }

  export class WorkerTwo extends Worker {
    constructor();
  }
}
```

I have nothing related to `worker-loader` in `webpack.config.json`. My worker files are simply called WorkerOne.ts and WorkerTwo.ts. 

When I try and build:

```
(node:4566) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
(node:4566) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
/Users/fredley/dev/frontend/node_modules/webpack/lib/webworker/WebWorkerMainTemplatePlugin.js:100
			hash.update(`${this.outputOptions.publicPath}`);
			                    ^

TypeError: Cannot read property 'outputOptions' of undefined
    at /Users/fredley/dev/frontend/node_modules/webpack/lib/webworker/WebWorkerMainTemplatePlugin.js:100:24
    at SyncHook.eval [as call] (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at MainTemplate.updateHash (/usr/local/lib/node_modules/webpack/lib/MainTemplate.js:390:19)
    at Compilation.createHash (/usr/local/lib/node_modules/webpack/lib/Compilation.js:1647:21)
    at hooks.optimizeTree.callAsync.err (/usr/local/lib/node_modules/webpack/lib/Compilation.js:924:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/usr/local/lib/node_modules/webpack/lib/Compilation.js:881:27)
    at hooks.make.callAsync.err (/usr/local/lib/node_modules/webpack/lib/Compiler.js:464:17)
    at _err0 (eval at create (/usr/local/lib/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/usr/local/lib/node_modules/webpack/lib/Compilation.js:749:12)
    at processModuleDependencies.err (/usr/local/lib/node_modules/webpack/lib/Compilation.js:688:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by yamass** [comment] 2018-03-06 08:25
Same here with TypeScript 2.7.2, webpack 3.11.0 and worker-loader 1.1.1

Works with worker-loader 1.1.0.

**Comment by zjy01** [comment] 2018-05-29 08:53
still happend at `webpack@4.10.0` , `worker-loader@2.0.0`

**Comment by shellscape** [comment] 2018-05-29 11:17
@fredley @yamass @zjy01 I don't mean to be disrespectful in the slightest, but this is kind of debugging 101. My first stop was to search this repo for `outputOptions` just in case something was confusing webpack, which [returned no results](https://github.com/webpack-contrib/worker-loader/search?q=outputOptions&unscoped_q=outputOptions). Since nothing was returned, I examined the stack trace posted above again and realized that `worker-loader` _did not appear in the stack trace at all_. From that I can conclude that you've reported the issue in the wrong place, and that you would probably benefit from reporting that error in `webpack/webpack` instead.

Probably a legitimate error, but it looks like the error resides in the main webpack project.

**Comment by fredley** [comment] 2018-05-29 11:26
@shellscape Sorry, my bad. Upon a quick scan I saw `webpack/lib/webworker`, and that went into my head as `worker-loader`. It seems there's [an issue](https://github.com/webpack/webpack/issues/6792) on webpack already that seems similar, I'll add this as an example.

**Comment by shellscape** [comment] 2018-05-29 11:28
@fredley no worries. should we close this one?

**Comment by fredley** [comment] 2018-05-29 11:30
@shellscape It looks like it, although it seems that until webpack itself fixes the underlying problem, worker-loader will be incompatible with 4.0.0+.

**Comment by shellscape** [comment] 2018-05-29 11:33
OK we'll leave it open then as kind of a waystation for people looking for the cause.

**Comment by chinchang** [comment] 2018-10-16 19:03
Seems like you have 2 versions of webpack:
- /usr/local/lib/node_modules/webpack/
- /Users/fredley/dev/frontend/node_modules/webpack/
Try deleting one.

**Comment by rifler** [comment] 2019-03-04 08:48
@chinchang thank you for answer, this helps!

But I don't understand some points. I have 2 `git:` dependencies, both of them use `webpack` (different major versions) as dependency to run some build in postinstall.
So I have:
`./node_modules/webpack` (from `package1`)
`./node_modules/package2/node_modules/webpack`

What should I do in this kind of situation? Fortunately either of deps are mine, so I can sync webpack versions

**Comment by evilebottnawi** [comment] 2020-07-10 13:12
Update webpack to latest version, if the problem still occurs please open a new issue with reproducible test repo, sorry for delay, thanks for using webpack

**Closed by evilebottnawi** 2020-07-10 13:12 UTC
Labels: priority: 3 (required), severity: 3 (broken), type: Bug
