### ISSUE TITLE
Loading workers doesn't work at all without inline mode

### ISSUE THREAD

**Issue by Zacqary** [webpack-contrib/worker-loader#26] opened 2016-06-23 14:44 UTC
I've only been able to get the Worker Loader to work in inline mode. Compiling worker files separately results in the worker immediately triggering its `onerror` event — except `event.message` is undefined. No code inside the worker's .js file appears to be executed. I've even tried commenting out the entirety of a worker file save for a single `console.log` statement, and this doesn't execute either.

My Webpack config includes:

```
postLoaders: [{
    test: /\.worker\.js$/,
    loader: "worker-loader?inline=true"
}],
```

when it works. Changing `loader` to `"worker-loader"` causes the failure.

I'm using these helper functions to interact with workers:

``` javascript
//callWorker.js

// Returns a promise that resolves after a web worker sends its next message
export function nextWorkerMessage(worker, terminate = false) {
    return new Promise((resolve, reject) => {
        worker.onmessage = ({data}) => {
            worker.onmessage = null;
            worker.onerror = null;
            if (terminate) worker.terminate();
            resolve(data);
        };
        worker.onerror = ({message}) => {
            worker.onmessage = null;
            worker.onerror = null;
            worker.terminate();
            reject(message);
        };
    });
}

// Create a new web worker from a constructor, then pass the args in a
// postMessage. Returns a promise that resolves after its next message, and
// then terminates the worker.
export default function callWorker(workerConstructor, ...args) {
    let worker = new workerConstructor();
    const promise = nextWorkerMessage(worker, true);
    const message = [...args];
    // If there are multiple args, pass them as an array. If there's
    // only one, pass it by itself
    if (message.length > 1) {
        worker.postMessage([...args]);
    } else {
        worker.postMessage(args[0]);
    }
    return promise;
}
```

And then in my app, something like this:

``` javascript
import callWorker from "callWorker";
import MyWorker from "myWorker.worker.js"; // Webpack is configured to load this with worker-loader

async function mainFn() {
    const result = await callWorker(MyWorker, "Send this message");
}
```

All of this works fine in inline mode, but disabling inline mode causes it to fail. I've even tried directly importing `MyWorker` in the same file where `callWorker` is defined to see if that cleared things up, but it didn't.

I'm not really sure how to go about debugging this further.

**Comment by abelnation** [comment] 2016-07-28 23:32
I am having this same issue.  

When not using inline, I have noted that instantiating the web worker results in a web request being made to the incorrect path.  

webpack.config.js

```

var path = require('path');

module.exports = {
    context: __dirname,
    entry: './main.js',
    output: {
        path: __dirname + '/dist',
        filename: 'bundle.js'
    },
    module: {
        loaders: [
            {
                test: /(viz|actions|api|data|reducers|store|workers)\/([^/]*\/)*[^/]*\.js$/,
                loader: 'babel-loader',
                exclude: /(node_modules|bower_components)/,
                query: {
                    presets: ['es2015']
                }
            }
        ],
    },

    devtool: 'source-map',
    devServer: {
        contentBase: '.'
    }
};
```

build results in files:

- js/dist/bundle.js
- js/dist/bundle.js.map
- js/dist/[hash].worker.js
- js/dist/[hash].worker.js.map

but i see requests to my local web server for:

```
127.0.0.1 - - [28/Jul/2016 16:17:13] "GET /c59704cab25e47f1681a.worker.js HTTP/1.1" 404 -
```

**Comment by abelnation** [comment] 2016-07-29 00:08
I was able to solve the issue by adding the following in my entry js file:

```
__webpack_public_path__ = '/js/dist/';
```

I tried setting `output.publicPath`, but that did not address the issue.

**Comment by michael-ciniawsky** [comment] 2017-10-12 11:51
Duplicate of #96

**Closed by michael-ciniawsky** 2017-10-12 11:51 UTC

**Comment by giuseppeg** [comment] 2018-03-29 13:43
@michael-ciniawsky I am experiencing a similar issue to @abelnation's. Where I get a 404 even when I set  `__webpack_public_path__` in my entry module.

My webpack conf looks like this:

```js
{
  entry: {
    app: path.resolve('./src/index.js'),
  },
  output: {
    path: path.resolve('./dist/development'),
    publicPath: '/',
    filename: '[name].js',
    libraryTarget: 'umd',
    library: 'MYLib',
    chunkFilename: 'chunks/[name].js'
  },
  resolve: {
    modules: [path.resolve('./src'), path.resolve('./node_modules')],
  },
}
```

and I import the worker like this:

```js
import W from 'worker-loader?fallback=false!./W.js'
```

Should webpack emit `c59704cab25e47f1681a.worker.js` or the worker is bundled in `app`? I can see that it is emitting the source maps for it `c59704cab25e47f1681a.worker.js.map`

**Comment by giuseppeg** [comment] 2018-03-29 15:09
silly me I guess I just needed to emit the file :)

```js
import W from 'worker-loader?name=worker.js&fallback=false!./W.js'
```

```js
{
  entry: {
    app: path.resolve('./src/index.js'),
    worker: path.resolve('./src/lib/worker.js'),
  },
  // ...
}
```
