### ISSUE TITLE
Need to load modules from other chunks

### ISSUE THREAD

**Issue by jnields** [webpack-contrib/worker-loader#90] opened 2017-08-24 21:54 UTC
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
When importing modules in a worker, all module code is included, whether or not other chunks define the module elsewhere, and whether or not CommonsChunkPlugin is used.

**If the current behavior is a bug, please provide the steps to reproduce.**
There is an example of the current behavior at [this repo](https://github.com/jnields/worker-loader-example).

**What is the expected behavior?**
It should be possible to import chunks/modules via importScripts when possible.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Importing other chunks via importScripts from workers in order to access modules will drastically decrease worker size and load time.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

This issue is for Webpack 2.x.x with worker-loader 0.8.1

Related: #70 #86

**Comment by michael-ciniawsky** [comment] 2017-10-12 12:03
Duplicate of #70

**Closed** 2017-10-12 12:03 UTC
