### ISSUE TITLE
Support for prefetch

### ISSUE THREAD

**Issue by TCMiranda** [webpack-contrib/worker-loader#116] opened 2017-12-31 03:33 UTC
As documented here[1] workers can be preloaded. Since woker-loader abstracts the file's "url" I can't tell the best way to preload the script.

What would be appropriate approach to handle prefetching?
Thanks

[1] [MDN Preloading content - The basics](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#The_basics)

**Comment by aprilmintacpineda** [comment] 2018-12-14 07:16
almost 2019, still no answer?

**Comment by sanbornhilland** [comment] 2019-02-25 22:40
@aprilmintacpineda Can you confirm that using `preload-webpack-plugin` actually behaves as expected? I'm trying right now and there are a couple things that lead me to believe it's not doing what I want it to.

1. Running a lighthouse report gives me warnings about the worker scrips I'm trying to preload: `A preload <link> was found for "foo.worker.js" but was not used by the browser.`

1. I'm seeing several requests for the same resource which seems wrong.
<img width="1416" alt="screen shot 2019-02-25 at 5 38 43 pm" src="https://user-images.githubusercontent.com/8059361/53373720-46be6700-3924-11e9-9a07-811c02191d37.png">

**Comment by aprilmintacpineda** [comment] 2019-02-26 02:25
**A preload <link> was found for "foo.worker.js" but was not used by the browser.** already confirms that it works and was preloaded. The issue is that when you preload a particular file, the browser expects that you will use it immediately. If you wouldn't use it immediately, you could use `prefetch` instead.

> Link prefetching is a browser mechanism, which utilizes browser idle time to download or prefetch documents that the user might visit in the near future ~MDN

More information at https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ

The reason why it said **but was not used by the browser** is because lighthouse only goes to the page where you ran it, it doesn't navigate around. Therefore, if you are only using it for a particular route, it will be preloaded BUT *not* used.

A word of warning, don't overuse preload as it consumes network data which you might need for something better, only use preload for resources that you would need immediately like fonts and your main/vendors JS files.

**Comment by sanbornhilland** [comment] 2019-02-26 15:14
@aprilmintacpineda Gotcha. Thanks for the explanation that gives me some good information to keep moving forward with this.

Does that fact that two network requests show up not seem suspicious to you?

**Comment by aprilmintacpineda** [comment] 2019-02-27 02:15
Now that you mentioned it, yeah it does look suspicious. Seems that a script tag triggered the first request and then a JS code triggered the second request. I'm not sure how and why that happened though.

**Comment by danielroe** [comment] 2020-01-24 09:01
See https://bugs.chromium.org/p/chromium/issues/detail?id=946510 for some more info on why this is happening. The correct way to preload is almost certainly with `as=worker` but this is currently not supported.

**Comment by evilebottnawi** [comment] 2020-07-28 14:42
Let's close in favor https://github.com/webpack/webpack/projects/5#card-10780341, it should be solved on webpack side, workaround https://github.com/GoogleChromeLabs/preload-webpack-plugin, it will be part of core for webpack@5, sorry for delay and inconvenience, we really have a lot of work and we try to do everything faster

**Closed by evilebottnawi** 2020-07-28 14:42 UTC
