### ISSUE TITLE
Upgrade to webpack >= v2.0.0 causes output script to be larger

### ISSUE THREAD

**Issue by sathify** [webpack-contrib/worker-loader#74] opened 2017-05-25 23:30 UTC
We recently upgraded to `webpack2.5.1` which increased the bundle of worker.js script 

```
                                     Asset     Size  Chunks                    Chunk Names
            9ecf2d4a6705b3ec6e59.worker.js   4.6 MB          [emitted]  [big]
```

Before, 

```
                                 Asset     Size  Chunks             Chunk Names
            0a49cd42e52df7a50b2f.worker.js  3.29 MB          [emitted]
```
We require like below, 
```js
var RenderWorker = require('worker-loader?proxy=%2Fworkers%2F!../workers/website-renderer');
```

Also upgraded to latest ```worker-loader@8.0.0```

Thoughts and pointers would be much appreciated.

**Comment by michael-ciniawsky** [comment] 2017-07-04 13:52
@sathify We need more info about your setup to triage this

**Comment by michael-ciniawsky** [comment] 2017-10-12 12:01
Duplicate of #70

**Closed by michael-ciniawsky** 2017-10-12 12:01 UTC
