### ISSUE TITLE
Compatibility with webpack-dev-server HMR.

### ISSUE THREAD

**Issue by aprilmintacpineda** [webpack-contrib/worker-loader#174] opened 2018-12-12 07:19 UTC
![image](https://user-images.githubusercontent.com/21032419/49852829-2ea87280-fe20-11e8-9e01-aedee773a580.png)

![image](https://user-images.githubusercontent.com/21032419/49853099-09683400-fe21-11e8-9202-42db71c8811e.png)

The error is coming from the web worker because `window` is not available on web workers.

Turning off HMR will fix the error BUT I want to be able to use HMR for other stuff. Is there anything that the loader could do about this?

https://github.com/webpack/webpack-dev-server/issues/1595

**Comment by ethansisson** [comment] 2018-12-29 14:51
I'm also experiencing this issue.

**Comment by spencer-brown** [comment] 2019-01-04 22:14
jFYI - a workaround has been recommended on the Webpack side [here](https://github.com/webpack/webpack/issues/6642#issuecomment-417581675).

**Comment by masx200** [comment] 2019-06-23 23:56
'm also experiencing this issue

**Comment by masx200** [comment] 2019-06-24 00:04
output: {
       path: path.join(__dirname, 'dist'),
       filename: 'bundle.js'
       publicPath: 'http://localhost:3000',
       globalObject: 'this'
},

**Comment by masx200** [comment] 2019-06-29 15:09
https://github.com/webpack/webpack-dev-server/issues/1595


https://github.com/webpack/webpack/issues/6642

https://github.com/webpack-contrib/worker-loader/issues/174

**Comment by evilebottnawi** [comment] 2019-07-01 09:32
Somebody can create minimum reproducible test repo?

**Comment by kumar303** [comment] 2019-07-10 19:35
@evilebottnawi I don't know if it's very minimal but I used [create-react-app](https://facebook.github.io/create-react-app/) to make a simple example. https://github.com/kumar303/worker-loader-issue174

The readme has instructions. The app gives me: `ReferenceError: window is not defined`

If I understand correctly, I can change the webpack config to transform `window` into `this` but that's tricky with create-react-app. I'm still thinking of ways to solve it.

**Comment by evilebottnawi** [comment] 2019-07-10 19:38
@kumar303 it is happens only with webpack-dev-server?

**Comment by kumar303** [comment] 2019-07-10 19:39
yes, I think so. In create-react-app, `yarn start` starts up in development mode.

**Comment by evilebottnawi** [comment] 2019-07-10 19:44
@kumar303 if is happens only with webpack-dev-server, can you create issue in webpack-dev-server repo with reproducible test repo (no need minimum, just step how to reproduce problem)

**Comment by kumar303** [comment] 2019-07-10 20:27
The title is misleading but this issue already exists in webpack-dev-server; it seems to be about the same exact problem: https://github.com/webpack/webpack-dev-server/issues/1595

**Comment by evilebottnawi** [comment] 2019-07-10 20:36
@kumar303 i think we should solve this instead exclude some files from HMR, because it is not good solution

**Comment by evilebottnawi** [comment] 2019-07-10 20:36
Can you put example with reproachable steps in issue

**Comment by davidawad** [comment] 2019-07-11 16:02
I've been fighting with this issue for a few days. I can't seem to include pdfjs within create react app. 

See https://github.com/wojtekmaj/react-pdf/issues/190 https://github.com/developit/workerize-loader/issues/5 and https://github.com/facebook/create-react-app/issues/1574

**Comment by evilebottnawi** [comment] 2019-07-11 16:03
I will look this on weekend

**Comment by dangreen** [comment] 2019-08-30 17:40
Hi there 👋

This is my solution to disable HMR for workers:
https://github.com/TrigenSoftware/hmr-filter-webpack-plugin#usage

**Comment by evilebottnawi** [comment] 2020-07-14 18:23
Fixed in the master, ETA is the end of week, big sorry for delay

**Closed by evilebottnawi** 2020-07-14 18:23 UTC
