### ISSUE TITLE
Can't build production file

### ISSUE THREAD

**Issue by thojanssens** [webpack-contrib/worker-loader#176] opened 2018-12-27 10:48 UTC
I used _create react app_ to create my app. I ejected the config files as I had to add the following configs into webpack:
```
    output: {
      globalObject: 'this',
      //...
    module: {
      rules: [
        {
            test: /\.worker\.js$/,
            use: { loader: 'worker-loader' }
        },
        //...
```
But when I try to build for production (`npm run build`), no files are generated:
```
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:
```
No files shows up after `File sizes after gzip:` and the build folder only contains `favicon.ico` and `manifest.json`.

The application works though when I launch it with `npm start`.

I tried using `react-app-rewired` to avoid ejecting, but I have the same problem anyway + another set of problems, so I gave up with this library...

When I remove the code specific to web workers, the build then works.

webpack version is "4.19.1",
worker loader version is "^2.0.0"

**Comment by davidshore** [comment] 2019-01-07 10:38
I had the same problem. Adding this to webpack config managed to fix it:
```
optimization: {
    noEmitOnErrors: false,
    //...
```
The production build seems to work even though it reports errors during the build process.

**Comment by cshl0ve** [comment] 2019-01-08 01:19
@davidshore Thank you so much. I upgraded from CRA 1 to 2 and there was exactly the same issue. I set the webpack config so that the problem is completely resolved.

**Comment by snoopy1412** [comment] 2019-01-15 09:02
> ,

nice

**Comment by snoopy1412** [comment] 2019-01-15 09:02
> I had the same problem. Adding this to webpack config managed to fix it:
> 
> ```
> optimization: {
>     noEmitOnErrors: false,
>     //...
> ```
> The production build seems to work even though it reports errors during the build process.

nice thank you

**Comment by samuelcolvin** [comment] 2019-01-28 16:38
I'm getting the same error; `noEmitOnErrors: false` "fixes" the problem, but I'm slightly scared of the error which must be causing this which I can't see and I'm skipping.

Does anyone know what's actually causing this? A proper fix would be great.

thanks so much for the `worker-loader` package btw, it's great.

**Comment by sombek** [comment] 2019-02-16 02:35
Now it is exporting the files which is very good
but now when I want to use the function from chrome the console says:`Uncaught TypeError: Fr.a is not a constructor` also there is a weird action which is when I open the react up it says `importScripts` is not defined 

this is how am using the worker in my component:
```
import Worker from "./excel.worker";
// then in the class 
const worker = new Worker();
```

Note my worker is located within the directory of the component is that right?
```
src/MyComponent
   * MyComponent.js
   * excel.worker.js 
```


my excel.worker file:
```
if ('function' === typeof importScripts) {
    importScripts('http://localhost:5000/static/xlsx/shim.min.js');
    importScripts('http://localhost:5000/static/xlsx/cpexcel.js');
    importScripts('http://localhost:5000/static/xlsx/jszip.js');
    importScripts('http://localhost:5000/static/xlsx/xlsx.js');
}
//eslint-disable-next-line
self.addEventListener('message', (e) => {
    /* My Logic with e.data */
    return postMessage(e.data});
});
```

Please help :(

**Comment by sombek** [comment] 2019-02-16 13:14
OKAY all the sudden today it's working fine 🤕 
I did not even needed this 😮!!
```
optimization: {
    noEmitOnErrors: false,
    //...
```

**Comment by sombek** [comment] 2019-02-16 13:45
> Now it is exporting the files which is very good
> but now when I want to use the function from chrome the console says:`Uncaught TypeError: Fr.a is not a constructor` also there is a weird action which is when I open the react up it says `importScripts` is not defined
> 
> this is how am using the worker in my component:
> 
> ```
> import Worker from "./excel.worker";
> // then in the class 
> const worker = new Worker();
> ```
> Note my worker is located within the directory of the component is that right?
> 
> ```
> src/MyComponent
>    * MyComponent.js
>    * excel.worker.js 
> ```
> my excel.worker file:
> 
> ```
> if ('function' === typeof importScripts) {
>     importScripts('http://localhost:5000/static/xlsx/shim.min.js');
>     importScripts('http://localhost:5000/static/xlsx/cpexcel.js');
>     importScripts('http://localhost:5000/static/xlsx/jszip.js');
>     importScripts('http://localhost:5000/static/xlsx/xlsx.js');
> }
> //eslint-disable-next-line
> self.addEventListener('message', (e) => {
>     /* My Logic with e.data */
>     return postMessage(e.data});
> });
> ```
> Please help :(

Okay now it is working fine 
The weird thing today is not showing an errors in webpack console

**Comment by mib32** [comment] 2019-08-24 14:10
If you are using create-react-app, run this command from your app dir:

```
 npx eslint ./PATH_TO_YOUR_WORKER_FILE -c ./node_modules/eslint-config-react-app/index.js
```

This will show any errors preventing build.

**Comment by ortonomy** [comment] 2019-09-02 02:55
BTW the fix to get this working with ``worker-loader`` and ``react-app-rewired`` is creating a ``config-overrides.js`` file and putting this inside:

```js
module.exports = function override(config, env) {
  config.module.rules.push({
    test: /\.worker\.js$/,
    use: { loader: 'worker-loader' }
  })

  config.output.globalObject = '(self || this)'
  return config
}
```

Name your workers ``*.worker.js`` and production builds will work

@thojanssens

**Comment by l-pa** [comment] 2019-11-15 14:00
Solved by putting 

`/* eslint-disable */`

**Comment by evilebottnawi** [comment] 2020-07-13 15:18
Here difference problem, they are were reported:
- problems with `globalObject`
- problems with compatibility with webpack-dev-server
- problems with losing context of `importScripts`
- bug on `react-app-rewired`
I closed issue, because they already reported and some of them are fixes, other fixes will be in near future

**Closed by evilebottnawi** 2020-07-13 15:18 UTC
