### ISSUE TITLE
Make worker cacheable

### ISSUE THREAD

**Issue by sgrj** [webpack-contrib/worker-loader#19] opened 2016-02-19 16:04 UTC
Can the worker be made cacheable? I'm happy to create a pull request if it's possible.

**Comment by tobek** [comment] 2017-03-13 21:48
Maybe this was fixed since this issue was opened, but the worker should be cacheable by browsers, if that's what you mean. By default the worker script produced is named with a content-dependent hash in it (e.g. `2e9912589ce947ab1cf5.worker.js`).

If you override the output file name (e.g. `require('worker-loader?name=output-name.js!./source-file.js')`) then the hash is *not* included. However, you can use the text `[hash]` in the name, and it will be interpolated correctly. I've added this to the documentation with https://github.com/webpack-contrib/worker-loader/pull/53.

**Comment by TrySound** [comment] 2017-03-30 19:54
@renchap If you will find a solution I will be glad to accept it :)

**Comment by renchap** [comment] 2017-03-31 08:28
Unfortunately I have no idea what causes this, and I a quick glance has not helped, I am not very familiar with Webpack plugins internals. I was just trying to clarify the issue :)

**Comment by michael-ciniawsky** [comment] 2017-07-04 14:16
https://github.com/webpack-contrib/worker-loader/blob/master/index.js#L22 explicitly seems to disable caching,  the questions is if this is required for the loader to work correctly :) ?

**Comment by renchap** [comment] 2017-07-04 14:58
Looks like it has been added for Webpack 2 compat here: https://github.com/webpack-contrib/worker-loader/pull/24 by @dtinth, and confirmed it is needed by @sokra.

From what I understand, it creates 2 visible effects:
- some additional output at each compilation
- as a new name is generated for each compilation, this creates a lot of extra files in the output directory

**Closed** 2017-10-12 10:36 UTC
Labels: flag: Needs more info, status: Needs triage, type: Build
